services:
  app:
    build:
      context: /home/ubuntu/eta-app/streamlit
      dockerfile: dockerfile
    env_file:
      - /home/ubuntu/eta-app/streamlit/.env
    ports:
      - "8501:8501"
    restart: unless-stopped
